branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: cd src && npm run ci.tslint && cd ../demo-angular && npm run ci.tslint
    - stage: "Build"
    #   os: osx
    #   env:
    #     - Webpack="iOS"
    #   osx_image: xcode9.2
    #   language: node_js 
    #   node_js: "6"
    #   jdk: oraclejdk8
    #   script: cd demo-angular && npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    # - os: linux
    #   language: android
    #   env:
    #     - Webpack="Android"
    #   jdk: oraclejdk8
    #   before_install: nvm install 6.10.3
    #   script: cd demo-angular && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    - os: linux
      env: 
        - BuildAndroid="26"
      language: android
      jdk: oraclejdk8
      before_install: nvm install stable
      script:
        - cd src && npm i && npm run tsc && cd ../demo-angular && tns build android
    - os: osx
      env: 
        - BuildiOS="11"
        - Xcode="9.2"
      osx_image: xcode9.2
      language: node_js 
      node_js: "6"
      jdk: oraclejdk8
      script: 
        - cd src && npm i && npm run tsc && cd ../demo-angular && tns build ios

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable

